apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-keycloak
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`keycloak.local`)
      kind: Rule
      services:
        - name: my-keycloak
          port: 80