kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type}}
  selector:
    app: {{ .Values.appName }}
  ports:
    - nodePort: {{ .Values.service.port }}
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
