pgadmin4:
  env:
    email: datahub@kadaster.nl
    password: admin
    contextPath: /pgadmin
    variables:
      - name: PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD
        value: "False"
  persistentVolume:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
