apiVersion: v2

name: traefik2
appVersion: "1.16.0"
description: A Traefik based Kubernetes ingress controller
type: application
version: 1.0.3

dependencies:
  - name: traefik
    version: 31.0.0
    repository: oci://ghcr.io/traefik/helm