apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 33.0.0
# renovate: image=traefik
appVersion: v3.2.0
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: 🐛 http3 with internal service"
    - "fix: use correct children indentation for logs.access.filters"
    - "fix(schema): :bug: targetPort can also be a string"
    - "fix(certificateResolvers)!: :boom: :bug: use same syntax in Chart and in Traefik"
    - "fix(Traefik)!: :boom: set 8080 as default port for `traefik` entrypoint"
    - "fix(Traefik Hub): RBAC for distributedAcme"
    - "fix(Kubernetes Ingress)!: :boom: :sparkles: enable publishedService by default"
    - "fix(Gateway API): :bug: add missing required RBAC for v3.2 with experimental Channel"
    - "fix(Env Variables)!: allow extending env without overwrite"
    - "feat(deps): update traefik docker tag to v3.2.0"
    - "feat(deps): update traefik docker tag to v3.1.6"
    - "feat(Traefik): ✨ support Gateway API statusAddress"
    - "feat(Traefik Proxy): CRDs for v3.2+"
    - "feat(Gateway API): :sparkles: standard install CRD v1.2.0"
    - "feat(Gateway API): :sparkles: add infrastructure in the values"
    - "chore: allow TRACE log level"
    - "chore(release): 🚀 publish v33.0.0"
    - "Update topology spread constraints comments"
