apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /whoami1
            backend:
              service:
                name: whoami
                port:
                  name: web